### PR TITLE
Adds video to homepage

### PR DESCRIPTION
**Pull request by dunkdunk**

### CODE REVIEW

**Comment by sjforman** [comment]
Only thing I notice is that the link at the end of the video to browse classes doesn't work. Is there a way to make a YouTube video have a clickable target _within_ it, as those last few frames call for?

**Comment by dunkdunk** [comment]
Interesting, is this on mobile? The clickable target is working for me.

**Comment by sjforman** [comment]
Hm...no...desktop...

screen shot 2015-08-17 at 5 52 57 pm

that link is active for you?

**Comment by dunkdunk** [comment]
Yes, it is active for me. There is a border that appears over the clickable area on hover.

I tried adjusting the video parameters to show/hide the controls, but it works in both cases for me.

screen shot 2015-08-17 at 2 56 44 pm

**Comment by sjforman** [comment]
Bizarre. Well, I'm going to go ahead and merge, anyway. Is probably just me, and no big deal either way + IMO not really worth trying to track down. Thanks!

**Comment by dunkdunk** [comment]
Hmmm yeah, very weird. I can't find an explanation as to why it wouldn't work for you. I wonder if it has something to do with Youtube preferences.

**Pull request merged**
